### ISSUE TITLE
[Beats] [Meta]: Only support shipping data to equal or newer version

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#29147]
Beats in the past allowed to ship data to newer and older versions of Elasticsearch of the same major. In most cases this worked but for older versions this posed some problems from time to time. There most common reasons is that Beats or a module started to use a feature in Elasticsearch that was not supported in previous version. This could be a new field type, new template structures or ingest pipeline features.

It was always recommended that Beats should be <= Elasticsearch version but it was never enforced. In Elastic Agent we started to enforce this to reduce support issues and reduce the support matrix. Beats 8.0 uses data streams and with this is only compatible to some of the 7.x releases of Elasticsearch. The upgrade path from 7.x to 8 is upgrading Elasticsearch first and then Beats. In general it should not happen that a user of Beats 8.0 is using Elasticsearch 7.x.

For Beats 8.0 I would like to introduce some compatibility check. Two proposals:

1. Beats 8.x can only ship to Elasticsearch 8.x (and newer)
2. Beats 8.x can only ship to Elasticsearch >= Beats

2 is a stricter variant of 1 and is what we do for Elastic Agent. It means if a user wants to upgrade Beats, Elasticsearch must be upgraded first. With this we will not have incompatibilities in features anymore. The check would be made on startup and connection to Elasticsearch.

- [x] #29263
- [x] #29264

**Comment by ruflin** [comment]
@kvch @nimarezainia @jlind23 @andresrc @mukeshelastic Please provide your feedback to the above. There is also an option to just document this and only enforce it in a second step. But I would prefer to have it enforced directly.

**Comment by nimarezainia** [comment]
@ruflin generally supportive of this idea if it applies to Beats 8.0 onwards. I would prefer to document and/or  a warning somewhere (not sure where since fleet is not in the picture) and let it work for the user rather than a heavy handed enforcement. Which in itself may create many SDH's - which would defeat the purpose all together.

I have read the two options multiple times and tbh I can't tell the difference between the two :-) sorry. Can you elaborate a bit more on how the second one is stricter?

**Comment by ruflin** [comment]
It applies to Beats 8.0 on onwards. The error would be in the logs of Beats. The documented approach we have followed so far but I see many deployments out there that do not follow this recommendation. I rather warn a user on upgrading Beats instead of later telling the user that had it running for a while that it is not supported.

The difference between the two options is as following:

1. Beats 8.4 can ship data to Elasticsearch 8.2
2. Beats 8.4 CAN'T ship data to Elasticsearch 8.2, only >=8.4 (like Elastic Agent)

**Comment by axrayn** [comment]
Hi @ruflin,

Hope you don't mind customer input here. :)

I agree that from a supportability perspective that this would be a good change.

We have a decent sized ECE deployment and about 10-12k host-based Beats instances so, for us, updating Elasticsearch first is somewhat of a no brainer.

That said, we do have some edge cases where we use specific containerised Beats for remote collections such as the vsphere metricbeat module.

For us, updating one of our ES clusters can take between 4-6 weeks when we account for updating lower environments and our change process. Updating those one off containers, we can do in a week. I know it won't be a common occurrence, but I can see there being times when I'd want to be able to update that Metricbeat container for a bugfix or an important new feature faster than I can update the receiving ES cluster.

As a potential third option to your question, could we enforce as option 2 by default but add an override config option to the Beat as a "yes i know I'm being dumb and this may not work right, but I accept that" that reverts it to option 1?

**Comment by ruflin** [comment]
@axrayn Appreciate it that you chime it in. You mention bug fixes, are you only thinking of bugfix releases or also minor releases? For example I expect Beats 8.2.2 to work with Elasticsearch 8.2.0. But I'm also aware that as soon as 8.3 is out, all the bug fixes from now on only land there.

I like your idea of the config flag. It would also make it very easy for us to see that someone disabled it when there are issue. In addition, it is a "concious" thing the user does, so if errors like "incompatible types" appear it, it easier to figure out way and doesn't come out of the blue.

There is a third option I was thinking of to have a compatibility range of something like -2 minors. Even though from an implementation perspective in Beats this would be simple, I think the mental model around it is too complex and unexpected. 8.3 Beats work with 8.1 ES and now users upgrades a minor and suddenly things stop working? Very surprising.

Currently my preferred option is 2a proposed by @axrayn : We enforce the compatibility of 2) but give users an option to opt out an go for 1).

**Comment by axrayn** [comment]
In terms of bug fixes, I was thinking more around updates that fix either a CVE or a known problem in a given module. Only other time I might get caught out by this is if I'm writing my own beat and accidentally base it off master instead of the latest major release (e.g. 7.x) branch. This should be somewhat of a moot point moving over to integrations though.

**Comment by P1llus** [comment]
@ruflin We also would need to remember to change the support matrix to mirror this somehow if that is the plan to enforce but allow overrides?

**Comment by jlind23** [comment]
Decision taken with @ruflin and @nimarezainia 
- A simple deprecation warning in 8.0
- An enforcement in 8.1

**Comment by ruflin** [comment]
@jlind23 To make sure we are on the same page. Enforcement in 8.1 but with a config option to opt out.

@nimarezainia Lets make sure this is properly shown in the compatibility matrix already in 8.0

**Comment by jlind23** [comment]
@ruflin can we close this as all related PR have been merged?
