### PR TITLE
Re-factor to fix high CPU usage on windows

### LINKED ISSUE #1460: Strange Topbeat (v1.2.1) Performance (under Windows)
Hi,
I have configured Topbeat with FILE output only:
Test OS is Windows 7 Enterprise and Topbeat version is v1.2.1.
```
input:
  period: 15
  procs: [".*"]
  stats:
    system: true
    process: true
    filesystem: true
    cpu_per_core: false
```
If I specify the "procs"-regex-filter with ".*", then I see no CPU consumption (great). Only every 15secs there is a short spike because of storing to file.

If I configure the "procs"-regex-filter with any other filter (e.g.  ".*Notepad.*" or "Notepad") then I got a permanent CPU consumption over 5%.

So the output of all processes is much faster than to take only one process. But I can't configure all processes because in this case the file size is growing to fast!

Can you help me overcome this issue?

### PR DESCRIPTION
**Pull request by tsg**
This decouples getting the basic state information from getting the more
detailed information.  The reason is that filtering only needs the name, but
the code was getting all details and then apply filtering. Getting the command
line is expensive on Windows, so that contributed to #1460.

What made it worse is that due to filtering, the command line cache was
invalidated on each run, which explains why topbeat was consuming more CPU when
filtering out processes than when not.

Fixes #1460.

This also pre-compiles the regexps, which brings some slight CPU usage improvements
and uncovers compilation errors earlier.

### CODE REVIEW

**Comment by tsg** [comment]
Don't merge yet, please, I need to test if it all looks good under Windows.

File: topbeat/beater/topbeat.go [hunk 1]
```diff
@@ -115,7 +115,10 @@ func (t *Topbeat) Setup(b *beat.Beat) error {
 func (t *Topbeat) Run(b *beat.Beat) error {
 	var err error
 
-	t.procStats.InitProcStats()
+	err = t.procStats.InitProcStats()
```
Comment (tsg) [inline topbeat/beater/topbeat.go]: @ruflin this might conflict with #1081, let's see which PR gets merged first so we can updated the other.

File: topbeat/system/process.go [hunk 2]
```diff
@@ -211,20 +235,22 @@ func (procStats *ProcStats) GetProcStats() ([]common.MapStr, error) {
...
+				logp.Err("Error getting process details. pid=%d: %v", process.Pid, err)
+				continue
+			}
 
 			newProcs[process.Pid] = process
 
-			last, ok := procStats.ProcsMap[process.Pid]
-			if ok {
-				procStats.ProcsMap[process.Pid] = process
-			}
```
Comment (tsg) [inline topbeat/system/process.go]: @monicasarbu I wasn't sure about the reasoning behind this `if ok` branch. Seems like the ProcsMap will get overwritten anyway.

Comment (monicasarbu) [inline topbeat/system/process.go]: @tsg I think you can simply remove the entire `if` as ProcsMap is updated in "procStats.ProcMap = newProcs" below.

**Comment by tsg** [comment]
Tested on Windows and OS X, looks good and the CPU usage dropped significantly on Windows.

**Comment by ruflin** [comment]
@tsg #1081 and #1566 were both merged with changes in topbeat. Rebase on top of it probably makes sense even though there does not seem to be a conflict. `make fmt` and one topbeat test seem to be failing.

**Comment by tsg** [comment]
@ruflin there was one slight change in the API (InitProcesses now can return an error). I rebased and added a commit to add the error check to Metricbeat. Please have a look.

The test and go vet should also be fixed now.

**Comment by ruflin** [comment]
LGTM. Waiting for Travis...

**Comment by ruflin** [comment]
Merging without Travis as Travis seems to be stuck ...
