### PR TITLE
Revert "let the system/process metricset monitor a single PID (#39620)"

### PR DESCRIPTION
**Pull request by pchila**
## Proposed commit message
This reverts commit 43d5dd4342a9ff56f40fafe1ba2ad7ed0a03b6c3 introduced with PR #39620.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]

**Comment by rdner** [comment]
The failure seems to be caused by updating github.com/coreos/go-systemd/v22 

https://github.com/coreos/go-systemd/blob/7d375ecc2b092916968b5601f74cca28a8de45dd/internal/dlopen/dlopen_example.go#L24

according to our error message:

```
dlopen_example.cgo2.c:(.text+0x36): multiple definition of `my_strlen'; /tmp/go-link-1331529901/000031.o:dlopen_example.cgo2.c:(.text+0x36): first defined here
```

**Comment by pchila** [comment]
> The failure seems to be caused by updating github.com/coreos/go-systemd/v22
> 
> https://github.com/coreos/go-systemd/blob/7d375ecc2b092916968b5601f74cca28a8de45dd/internal/dlopen/dlopen_example.go#L24
> 
> according to our error message:
> 
> ```
> dlopen_example.cgo2.c:(.text+0x36): multiple definition of `my_strlen'; /tmp/go-link-1331529901/000031.o:dlopen_example.cgo2.c:(.text+0x36): first defined here
> ```

Interesting... in go.mod and go.sum of PR #39620 we can see that `go-systemd` has been updated
image

And in go.sum we see 2 versions of go-systemd but to have a duplicate definition we need to be linking the same symbol twice so:
- either  the module is compiled twice (2 diff versions) and linked twice
- some part of agent beat includes the same module multiple times from multiple beats

**Comment by andrewkroh** [comment]
coreos/go-systemd copied the code that includes this symbol from coreos/pkg. We use both. So now we have a conflict.

The symbol in question is purely test code so it should have been included in a file with a `_test.go` suffix.
